DROP TABLE IF EXISTS friends CASCADE;
DROP TABLE IF EXISTS film_likes CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS film_genres CASCADE;
DROP TABLE IF EXISTS films CASCADE;
DROP TABLE IF EXISTS mpa CASCADE;
DROP TABLE IF EXISTS genres CASCADE;

CREATE TABLE IF NOT EXISTS genres (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name varchar NOT NULL
);
CREATE TABLE IF NOT EXISTS mpa (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name varchar NOT NULL
);
CREATE TABLE IF NOT EXISTS films (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        name varchar NOT NULL,
        description varchar NOT NULL,
        release_date date NOT NULL,
        duration bigint,
        mpa_id integer REFERENCES mpa (id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS film_genres (
        film_id integer REFERENCES films (id) ON DELETE CASCADE,
        genre_id integer REFERENCES genres (id) ON DELETE CASCADE,
        CONSTRAINT film_genres_PK PRIMARY KEY (film_id,genre_id)
);
CREATE TABLE IF NOT EXISTS users (
        id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        email varchar NOT NULL,
        login varchar NOT NULL,
        name varchar,
        birthday date
);
CREATE TABLE IF NOT EXISTS film_likes (
        film_id integer REFERENCES films (id) ON DELETE CASCADE,
        user_id integer REFERENCES users (id) ON DELETE CASCADE,
        CONSTRAINT film_likes_PK PRIMARY KEY (film_id,user_id)
);
CREATE TABLE IF NOT EXISTS friends (
        user_id integer REFERENCES users (id),
        friend_id integer REFERENCES users (id),
        CONSTRAINT FRIENDS_PK PRIMARY KEY (USER_ID,FRIEND_ID)
);

INSERT INTO genres (name) VALUES ('Комедия');
INSERT INTO genres (name) VALUES ('Драма');
INSERT INTO genres (name) VALUES ('Мультфильм');
INSERT INTO genres (name) VALUES ('Триллер');
INSERT INTO genres (name) VALUES ('Документальный');
INSERT INTO genres (name) VALUES ('Боевик');
INSERT INTO mpa (name) VALUES ('G');
INSERT INTO mpa (name) VALUES ('PG');
INSERT INTO mpa (name) VALUES ('PG-13');
INSERT INTO mpa (name) VALUES ('R');
INSERT INTO mpa (name) VALUES ('NC-17');
INSERT INTO users (id, email, login, name, birthday) VALUES (5, 'mail@mail.ru', 'login', 'name', CAST('2000-01-01' AS DATE));
INSERT INTO films (id, name, description, release_date, duration, mpa_id) VALUES (5, 'nii', 'descriptions', CAST('1967-03-25' AS DATE), 100, 4);